version: "3.8"
services:
  api:
    build: .
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/usr/src/app

  db:
    image: postgres
    container_name: htn-db
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "123456"
      POSTGRES_DB: htn_challenge
    volumes:
      - data:/var/lib/postgresql/data
volumes:
  data: {}
